"""empty message

Revision ID: 281808040fc7
Revises: 38cd9701685e
Create Date: 2023-04-03 21:37:56.758697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281808040fc7'
down_revision = '38cd9701685e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('answer', 'create_data')
    op.add_column('question', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('question', 'create_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('question', 'create_date')
    op.add_column('answer', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
